set(NRD_USE_DX12 ON CACHE BOOL "" FORCE)
set(NRD_STATIC_LIBRARY ON CACHE BOOL "" FORCE)

set(NRD_EMBEDS_SPIRV_SHADERS OFF CACHE BOOL "" FORCE)
set(NRD_EMBEDS_DXBC_SHADERS OFF CACHE BOOL "" FORCE)

set(NRD_NORMAL_ENCODING "4" CACHE STRING "" FORCE)    # NRD_NORMAL_ENCODING_RGBA16_SNORM
set(NRD_ROUGHNESS_ENCODING "1" CACHE STRING "" FORCE) # NRD_ROUGHNESS_ENCODING_LINEAR

add_subdirectory(extern/NRD)

target_include_directories(
    ${PROJECT_NAME}
    PRIVATE
        "extern/NRD/Include"
)

target_link_libraries(
    ${PROJECT_NAME}
    PRIVATE
        NRD
)