set(OMM_PROJECT_FOLDER "OMM-Library")
set(OMM_ENABLE_TESTS OFF CACHE BOOL "" FORCE)
set(OMM_BUILD_VIEWER OFF CACHE BOOL "" FORCE)
set(OMM_INTEGRATION_LAYER_NVRHI OFF CACHE BOOL "")
set(OMM_STATIC_LIBRARY OFF CACHE BOOL "" FORCE)
set(OMM_OUTPUT_BIN_PATH "${CMAKE_RUNTIME_OUTPUT_DIRECTORY}")
add_subdirectory(extern/OMM)

target_compile_options(omm-lib PRIVATE
    /WX-
)

target_link_libraries(${PROJECT_NAME} PRIVATE omm-lib)

